In [2]:
import numpy as np

In [7]:
array = np.array([0, 1, 2, 3, 4, 5])
print(type(array))
print(array)

<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [8]:
array = np.array([[0], [1], [2]])
print(array)

[[0]
 [1]
 [2]]


In [9]:
array = np.array([[0, 1, 2], [3, 4, 5]])
print(array)
print(array.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


In [10]:
na = np.array([0, 1, 2, 3, 4, 5, 6, 7])
na

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
na.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [13]:
a
a.ndim

2

In [14]:
b = a[:2, 1:3]

In [15]:
b

array([[2, 3],
       [6, 7]])

In [16]:
b[0, 0]

2

In [17]:
print(b)

[[2 3]
 [6 7]]


In [18]:
b[0, 0] = 77

In [19]:
a[0, 0]

1

In [20]:
a[0, 1]

77

In [21]:
i = a.T

In [22]:
i

array([[ 1,  5,  9],
       [77,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [23]:
i.ndim

2

In [24]:
hazard = np.array([[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]], [[0, 1, 2, 3],[4, 5, 100, 7], [8, 9, 10, 11]]])


In [25]:
array.ndim

2

In [26]:
hazard
hazard.ndim

3

In [27]:
eden = hazard[1:, 1:, 2:]
print(eden)
print(eden.ndim, eden.shape)

[[[100   7]
  [ 10  11]]]
3 (1, 2, 2)


In [28]:
eden[0].ndim

2

In [29]:
data = np.zeros(5, dtype=int)

In [30]:
data

array([0, 0, 0, 0, 0])

In [31]:
data[1] = 1

In [32]:
data

array([0, 1, 0, 0, 0])

In [33]:
i = np.zeros([3,4])

In [34]:
i.ndim

2

In [35]:
i

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
i = np.array([1,2,3,4,5])

In [37]:
i.ndim

1

In [38]:
n = np.array([1,2,3,4,5])

In [39]:
n.ndim

1

In [40]:
lee = np.zeros((2,3,3))

In [41]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
ls = np.ones_like(lee)

In [43]:
ls

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [44]:
p = np.empty((5,5))
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.linspace(0, 30, 6)

array([ 0.,  6., 12., 18., 24., 30.])

In [51]:
np.random.seed(0)
rd = np.random.rand(10) 
print(rd)

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]


In [62]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [64]:
r = np.random.rand(2,3,4)
print(r)

[[[0.89460666 0.08504421 0.03905478 0.16983042]
  [0.8781425  0.09834683 0.42110763 0.95788953]
  [0.53316528 0.69187711 0.31551563 0.68650093]]

 [[0.83462567 0.01828828 0.75014431 0.98886109]
  [0.74816565 0.28044399 0.78927933 0.10322601]
  [0.44789353 0.9085955  0.29361415 0.28777534]]]


In [4]:
t = np.random.randint(2,5,(4,4))
print(t)

[[2 3 4 3]
 [4 2 4 3]
 [3 2 2 2]
 [4 3 3 2]]


In [75]:
a = np.random.randint(10,size=(3,4))

In [76]:
a

array([[3, 0, 8, 4],
       [2, 9, 0, 3],
       [8, 1, 4, 3]])

In [77]:
a

array([[3, 0, 8, 4],
       [2, 9, 0, 3],
       [8, 1, 4, 3]])

In [81]:
np.random.shuffle(a)
a

array([[3, 0, 8, 4],
       [8, 1, 4, 3],
       [2, 9, 0, 3]])

In [5]:
index, count = np.unique(a, return_counts=True)
print(index)
print(count)

NameError: name 'a' is not defined

In [4]:
na1 = np.arange(6)

In [1]:
import numpy as np

In [5]:
na1

array([0, 1, 2, 3, 4, 5])

In [7]:
na2 = np.arange(6,12)
na1 = np.random.randint(10, size=(2,3))
na2 = np.random.randint(10, size=(2,3))
print(na1)
print(na2)

[[6 7 9]
 [7 6 6]]
[[2 7 5]
 [8 8 7]]


In [8]:
na3 = np.stack((na1, na2))
print(na3)

[[[6 7 9]
  [7 6 6]]

 [[2 7 5]
  [8 8 7]]]


In [3]:
na3 = np.stack((na1, na2), axis=1)
print(na3)

NameError: name 'na1' is not defined

In [4]:
ls = []
for i in range(5):
    print(range(7), i, i+3)
    print(range(7)[i:i+3])
    print(list(range(7)[i:i+3]), end="\n\n")
    ls.append(range(7)[i:i+3])

range(0, 7) 0 3
range(0, 3)
[0, 1, 2]

range(0, 7) 1 4
range(1, 4)
[1, 2, 3]

range(0, 7) 2 5
range(2, 5)
[2, 3, 4]

range(0, 7) 3 6
range(3, 6)
[3, 4, 5]

range(0, 7) 4 7
range(4, 7)
[4, 5, 6]



In [5]:
np.vstack(ls)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [7]:
np.hstack(ls)

array([0, 1, 2, 1, 2, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6])

In [8]:
a = [list(range(7)[i:i+3]) for i in range(5)]
print(a)

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]


In [11]:
np.arange(5)[:3, np.newaxis]

array([[0],
       [1],
       [2]])