In [2]:
import numpy as np

In [6]:
r1 = np.random.randint(10, size=(2,3))
print(r1, r1.shape)

[[1 1 2]
 [5 8 9]] (2, 3)


In [9]:
r2 = np.random.randint(10, size=(3,2))
print(r2, r2.shape)

[[0 5]
 [0 4]
 [0 3]] (3, 2)


In [10]:
r3 = np.random.randint(10, size=(3,3))
print(r3, r3.shape)

[[9 5 3]
 [9 0 5]
 [3 4 2]] (3, 3)


In [11]:
np.concatenate([r1, r3])

array([[1, 1, 2],
       [5, 8, 9],
       [9, 5, 3],
       [9, 0, 5],
       [3, 4, 2]])

In [15]:
np.concatenate([r2, r3], axis=1)

array([[0, 5, 9, 5, 3],
       [0, 4, 9, 0, 5],
       [0, 3, 3, 4, 2]])

In [16]:
r = np.arange(0,10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
r1, r2 = np.split(r, [5])
r1

array([0, 1, 2, 3, 4])

In [20]:
r2

array([5, 6, 7, 8, 9])

In [22]:
a = np.random.randint(10, size=(4,6))
a

array([[1, 8, 7, 2, 6, 2],
       [7, 5, 8, 8, 4, 8],
       [3, 2, 2, 6, 7, 8],
       [9, 8, 4, 3, 0, 0]])

In [25]:
a1, a2 = np.vsplit(a, [2])
print(a1)
print(a2)

[[1 8 7 2 6 2]
 [7 5 8 8 4 8]]
[[3 2 2 6 7 8]
 [9 8 4 3 0 0]]


In [35]:
a1, a2, a3 = np.hsplit(a, [2,4])
print(a1)
print(a2)

[[1 8]
 [7 5]
 [3 2]
 [9 8]]
[[7 2]
 [8 8]
 [2 6]
 [4 3]]


In [42]:
result = np.arange(1, 10)
result

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
result = np.reshape(result, (3,3))
result

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
np.random.shuffle(result)

In [46]:
result

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [51]:
ls = [1,2,3,4,5]
print("before : {}".format(ls))
for idx in range(len(ls)):
    ls[idx] = ls[idx] * 3
print("after : {}".format(ls))

before : [1, 2, 3, 4, 5]
after : [3, 6, 9, 12, 15]


In [52]:
na = np.array(ls)
print(na)
na *= 3
print(type(na), na)

[ 3  6  9 12 15]
<class 'numpy.ndarray'> [ 9 18 27 36 45]


In [53]:
na_2 = np.array([6,7,8,9,10])
result = na * na_2
print("{}\n{}\n{}".format(na, na_2, result))

[ 9 18 27 36 45]
[ 6  7  8  9 10]
[ 54 126 216 324 450]


In [54]:
idx = na_2 % 3 == 0
print(idx)

[ True False False  True False]


In [55]:
print(na_2[idx])

[6 9]


In [57]:
na1 = np.array([1,2,3,4,5])
na2 = np.array([1,3,4,5,5])
print(na1 == na2)
print(na1[na1 == na2])


[ True False False False  True]
[1 5]


In [59]:
na1 = np.arange(6)
na2 = np.arange(6,12)
print("array1 : {}".format(na1))
print("array2 : {}".format(na2))

array1 : [0 1 2 3 4 5]
array2 : [ 6  7  8  9 10 11]


In [62]:
print("scala : {}".format(na1 * 10))
print("vector : {}".format(na1 * na2))

scala : [ 0 10 20 30 40 50]
vector : [ 0  7 16 27 40 55]


In [67]:
na3 = na1.reshape(2,3)
na4 = na2.reshape(2,3)
print("array3 : \n{}".format(na3))
print("array4 : \n{}".format(na4))
print("matrix : \n{}".format(na3 * na4))

array3 : 
[[0 1 2]
 [3 4 5]]
array4 : 
[[ 6  7  8]
 [ 9 10 11]]
matrix : 
[[ 0  7 16]
 [27 40 55]]


In [71]:
na1 = np.arange(12)
na2 = na1.reshape(3,4)
print("na1 : \n{}".format(na1))
print("na2 : \n{}".format(na2))

na3 = np.ones_like(na1)
na3 = na3.reshape(3,4)
print("na3 : \n{}".format(na3))


na1 : 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
na2 : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
na3 : 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [72]:
print("na2 + 1 : \n{}".format(na2 + 1))
print("na2 + na3 : \n{}".format(na2 + na3))

na2 + 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
na2 + na3 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [76]:
na4 = np.arange(4)
print("na2 : \n{}".format(na2))
print("na4 : \n{}".format(na4))
print("na2 + na4 : \n{}".format(na2 + na4))

na5 = np.stack((na4, na4, na4))
print("na5 : \n{}".format(na5))
print("na2 + na5 : \n{}".format(na2 + na5))

na2 : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
na4 : 
[0 1 2 3]
na2 + na4 : 
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]
na5 : 
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
na2 + na5 : 
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [86]:
na6 = np.arange(3)[:, np.newaxis]
print("na2 : \n{}".format(na2))
print("na6 : \n{}".format(na6))
print("na2 + na6 : \n{}".format(na2 + na6))
na7 = np.array([[i for _ in range(4)] for i in range(3)])
print("na7 : \n{}".format(na7))
print("na2 + na7 : \n{}".format(na2 + na7))

na2 : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
na6 : 
[[0]
 [1]
 [2]]
na2 + na6 : 
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]
na7 : 
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
na2 + na7 : 
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


In [89]:
c = np.random.rand(2,3)
c_num = np.arange(5)
c_num = (c*10).astype('int64')
print("random matrix : \n{}".format(c_num))
print("min : {}".format(c_num.min()))
print("max : {}".format(c_num.max()))


random matrix : 
[[7 7 8]
 [7 8 6]]
min : 6
max : 8


In [94]:
print("argmin : {}".format(c_num.argmin()))
print("argmax : {}".format(c_num.argmax()))
print("mean : {}".format(c_num.mean()))

argmin : 5
argmax : 2
mean : 7.166666666666667


In [101]:
d = np.random.rand(2,3)
d_num = np.arange(5)
d_num = (d*10).astype('int64')
print("random matrix : \n{}".format(d_num))
print("sum : {}".format(np.sum(d_num)))
print("sum_axis_0 : {}".format(np.sum(d_num, axis=0)))
print("sum_axis_1 : {}".format(np.sum(d_num, axis=1)))
print("median : {}".format(np.median(d_num)))

random matrix : 
[[8 4 9]
 [3 7 0]]
sum : 31
sum_axis_0 : [11 11  9]
sum_axis_1 : [21 10]
median : 5.5


In [102]:
print("std : {}".format(np.std(d_num)))
print("var : {}".format(np.var(d_num)))

std : 3.131382371342656
var : 9.805555555555555


In [103]:
n1 = np.array(range(3,8))
n2 = n1
n3 = np.array(range(1,11,2))
print(n1, n2, n3, end="\n\n")
print(n1 == n2)
print(np.all(n1 == n2))
print(n1 == n3)
print(np.all(n1 == n3))
print(n1 > n3)
print(np.all(n1 > n3))

[3 4 5 6 7] [3 4 5 6 7] [1 3 5 7 9]

[ True  True  True  True  True]
True
[False False  True False False]
False
[ True  True False False False]
False


In [2]:
import numpy as np

In [3]:
n1 = np.array(range(3, 8))
n2 = n1
n3 = np.array(range(1,11,2))
print(n1, n2, n3, end = "\n\n")
print(n1 != n2)
print(np.any(n1 != n2))
print(n1 == n3)
print(np.any(n1 == n3))
print(n1 > n3)
print(np.any(n1 > n3))

[3 4 5 6 7] [3 4 5 6 7] [1 3 5 7 9]

[False False False False False]
False
[False False  True False False]
True
[ True  True False False False]
True


In [4]:
na = np.array([num for num in range(0, 101)])
print(na)
np.percentile(na, 25), np.percentile(na, 45)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


(25.0, 45.0)

In [5]:
na = np.arange(1, 6)
print(na)
print(np.log(na))

[1 2 3 4 5]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [6]:
ls = []
size = int(1E7)
for data in range(size):
    ls.append(data)
na = np.array(ls)

In [8]:
count = 0
for idx in range(len(ls)):
    if (ls[idx] % 3 == 0) or (ls[idx] % 5 == 0):
        count += 1
print(count)

4666667


In [10]:
count = len(na[(na%3 == 0) | (na%5 == 0)])
print(count)

4666667


In [13]:
count = len(na[(na%4 == 0) | (na%7 == 0)])
print(count)

3571429


In [14]:
data1 = np.random.randint(10, size=20)
data1.sort()
data1

array([0, 0, 1, 2, 2, 2, 3, 4, 4, 4, 4, 6, 6, 6, 7, 7, 7, 8, 9, 9])

In [16]:
data2 = np.random.randint(10, size=20)
data2.sort()
data2

array([0, 0, 0, 0, 2, 2, 2, 4, 4, 4, 5, 5, 6, 6, 6, 7, 8, 9, 9, 9])

In [17]:
data3 = np.random.randint(10, size=20)
data3.sort()
data3 = data3[::-1]
data3

array([9, 8, 7, 7, 7, 7, 6, 6, 5, 5, 5, 5, 4, 3, 3, 3, 3, 1, 1, 0])

In [18]:
np.corrcoef(data1, data2)[0][1]

0.9737930132833887

In [19]:
np.corrcoef(data1, data3)[0][1]

-0.9713937642900439

In [20]:
data4 = np.random.randint(10, size=20)
data5 = np.random.randint(10, size=20)

In [3]:
np.corrcoef(data4, data5)[0][1]

NameError: name 'data4' is not defined

In [4]:
import numpy as np
import numpy as pd

In [5]:
data = pd.Series(np.random.randint(10, size=5)) 
data

AttributeError: module 'numpy' has no attribute 'Series'

In [6]:
pd.test()

NumPy version 1.15.1
NumPy relaxed strides checking option: True
.................x...................................................... [  1%]
........................................................................ [  2%]
........................................................................ [  4%]
................................................s................x.x.... [  5%]
........................................................................ [  7%]
........................................................................ [  8%]
.............................................sss........................ [  9%]
........................................................................ [ 11%]
..s.....................xx.............................................. [ 12%]
........................................................................ [ 14%]
.................................................................ss..... [ 15%]
.......................................................

1.4142135623730951

F..s........... [ 32%]
........................................................................ [ 34%]
........................................................................ [ 35%]
........................................................................ [ 37%]
........................................................ss.s..s.......s. [ 38%]
........................................................................ [ 39%]
.............................FFsssssssssssssssssssssssssssssssssssssssss [ 41%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 42%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 44%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 45%]
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss [ 47%]
sssssssssssssssssssssssssssssssssss..................................... [ 48%]
.................s...................................................... [ 49%]
.................

            if opt not in ccomp_s:
                ccomp_s = ccomp_s.replace(gcv_opt, opt)
                self.compiler_so = ccomp_s.split()
            llink_s = " ".join(self.linker_so)
            if opt not in llink_s:
                self.linker_so = llink_s.split() + opt.split()
    
        display = '%s: %s' % (os.path.basename(self.compiler_so[0]), src)
    
        # gcc style automatic dependencies, outputs a makefile (-MF) that lists
        # all headers needed by a c file as a side effect of compilation (-MMD)
        if getattr(self, '_auto_depends', False):
            deps = ['-MMD', '-MF', obj + '.d']
        else:
            deps = []
    
        try:
            self.spawn(self.compiler_so + cc_args + [src, '-o', obj] + deps +
                       extra_postargs, display = display)
        except DistutilsExecError:
            msg = str(get_exception())
>           raise CompileError(msg)
E           distutils.errors.CompileError: Command "gcc -Wno-unused-resu

  output = mkl_fft.rfft_numpy(a, n=n, axis=axis)

/anaconda3/lib/python3.7/site-packages/mkl_fft/_numpy_fft.py:158: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  output = mkl_fft.fft(a, n, axis)
/anaconda3/lib/python3.7/site-packages/mkl_fft/_numpy_fft.py:676: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  output = mkl_fft.fftn(a, s, axes)

/anaconda3/lib/python3.7/site-packages/mkl_fft/_numpy_fft.py:158: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In t

False

In [1]:
import numpy as np

In [10]:
a = np.linspace(0, 100, 11)

In [11]:
a

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [16]:
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

In [19]:
np.logspace(2, 8, 3)

array([1.e+02, 1.e+05, 1.e+08])